# Generated by Django 2.2.16 on 2022-08-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220803_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='Код подтверждения'),
        ),
    ]
