# Generated by Django 2.2.16 on 2022-08-05 08:00

from django.db import migrations, models
import reviews.validations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220804_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, null=True, validators=[reviews.validations.validate_year]),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='###', max_length=10, null=True, verbose_name='Код подтверждения'),
        ),
    ]
